<?php

use Illuminate\Database\Seeder;

class PostsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('posts')->insert([
            [
                'body'=>'ギア５強すぎ',
                'user_id'=>1,
                'comic_id'=>1,
                'type'=>1,
                'episode'=>1045
            ],
            [
                'body'=>'工藤新一がコナンってこと？',
                'user_id'=>2,
                'comic_id'=>4,
                'type'=>0,
                'episode'=>1
            ],
            [
                'body'=>'エネルの天敵ルフィだけやな',
                'user_id'=>3,
                'comic_id'=>1,
                'type'=>0,
                'episode'=>30
            ],
            [
                'body'=>'火影になった！',
                'user_id'=>4,
                'comic_id'=>2,
                'type'=>0,
                'episode'=>72
            ],
            [
                'body'=>'犯人は毛利小五郎',
                'user_id'=>5,
                'comic_id'=>4,
                'type'=>1,
                'episode'=>700
            ],
            [
                'body'=>'いずくって読んだ！',
                'user_id'=>6,
                'comic_id'=>3,
                'type'=>1,
                'episode'=>322
            ],
            [
                'body'=>'もともとデクにも個性ある説',
                'user_id'=>7,
                'comic_id'=>3,
                'type'=>0,
                'episode'=>10
            ],
            [
                'body'=>'ガイ先生ってこんな強いの、カカシより強いんじゃね',
                'user_id'=>8,
                'comic_id'=>2,
                'type'=>1,
                'episode'=>640
            ],
            [
                'body'=>'チョッパーかわいい、ペット枠いいね',
                'user_id'=>2,
                'comic_id'=>1,
                'type'=>0,
                'episode'=>17
            ]
        ]);
    }
}
